### ISSUE TITLE
Check actions parameter has wrong type

### ISSUE THREAD

**Issue by laughedelic** [octokit/routes#167]
- endpoint scope: check-runs
- endpoint name: update-a-check-run
- route: `PATCH /repos/:owner/:repo/check-runs/:check_run_id`
- documentation URL: https://developer.github.com/v3/checks/runs/#update-a-check-run

### Current specification

https://github.com/octokit/routes/blob/d8c3b5db9c9d1f7cef7bf2afbbf7e1382b309a8f/routes/checks/runs/update-a-check-run.json#L215-L221

### I expected

It should be an array of action objects.

----

I'm not sure if I'm opening this issue in the right place. I think it's not just about the routes specification.

* if I pass an object, as is required by the current specification, I get
    ```json
    {
      "message": "Invalid request.\n\nFor 'properties/actions', {\"label\"=>\"...\", \"description\"=>\"...\", \"identifier\"=>\"...\"} is not an array.",
      "documentation_url": "https://developer.github.com/v3/checks/runs/#update-a-check-run"
    }
    ```

    Notice "is not an array" part.

* and if I pass an array with the same object inside, I get

    ```
    Empty value for parameter 'actions.description': undefined
    ```

**Comment by gr2m** [comment]
Thanks @laughedelic for reporting the issue. Could you maybe provide a minimal test case? That will help the docs team to reproduce the problem. If you are right (and I assume you are) they’ll have to adopt the documentation at https://developer.github.com/v3/checks/runs/#update-a-check-run

![image](https://user-images.githubusercontent.com/39992/40759997-811bebd0-6449-11e8-894d-78e024273d40.png)

That will have to say `array of objects` instead

**Comment by gr2m** [comment]
actually nevermind, the example shows that it’s an array, I’m sure it was just a mistake. I got it

![image](https://user-images.githubusercontent.com/39992/40760130-2bc107f0-644a-11e8-8bb3-45514c61d167.png)

Is this a blocker for you? I can get it fixed before it’s fixed in the docs, it usually doesn’t take long though

**Comment by laughedelic** [comment]
Thanks. No, it's not a blocker for me, I have plenty of other stuff to do meanwhile. I was just exploring the check API and wanted to try and see how actions look. This is is far on the roadmap for the bot I'm working on.

I'm not sure that just changing the docs (and re-generating the routes) will fix the problem. I tried to pass an array of objects, but got this `Empty value for parameter 'actions.description': undefined` error. Could you clarify where does it come from?

**Comment by gr2m** [comment]
I guess you are using `@ocotkit/rest`? The error is coming from here: https://github.com/octokit/rest.js/blob/65bc7f9cae94d49b574e4f2a8a85b1d501a17d58/lib/plugins/endpoint-methods/validate.js#L80

Try to edit `node_modules/@octokit/rest/lib/routes.json` directly and change actions to `"type": "objects"` and the child properties to `"actions[].*"`. Compare https://github.com/octokit/rest.js/blob/master/lib/routes.json#L1110-L1124

**Comment by laughedelic** [comment]
Right, thanks for the explanation. I'll try the workaround later, but I'm just glad to know that it's a matter of a simple fix in the docs/routes, not a backend problem.

**Comment by gr2m** [comment]
this was resolved by https://github.com/octokit/routes/releases/tag/v9.1.2 🎉
