### ISSUE TITLE
Potentially missing route definition for repo issue events

### ISSUE THREAD

**Issue by kytrinyx** [octokit/routes#169]
- endpoint scope: Activity
- endpoint name: List issue events for a repository
- route: GET /repos/:owner/:repo/issues/events
- documentation URL: https://developer.github.com/v3/activity/events/#list-issue-events-for-a-repository

This endpoint is missing from the https://github.com/octokit/routes/blob/d8c3b5db9c9d1f7cef7bf2afbbf7e1382b309a8f/routes/activity.json file.

The odd thing is that we seem to have two endpoints for issue events on a repository.

- `GET /repos/:owner/:repo/issues/events` - [List events for a repository](https://developer.github.com/v3/issues/events/#list-events-for-a-repository)
- `GET /repos/:owner/:repo/issues/events` - [List issue events for a repository](https://developer.github.com/v3/activity/events/#list-issue-events-for-a-repository)

I'm trying to figure out why we have two that seem very similar (possibly one is legacy with a different structure).

Do you happen to have any knowledge about this? Do you recall whether you are explicitly skipping this endpoint, or is it an artifact of the parsing process?

**Comment by gr2m** [comment]
Yes I think they are the exact same? I ignored the one from activity/events

- Issue: https://github.com/octokit/routes/issues/130
- Commit: https://github.com/octokit/routes/pull/136/commits/2341cf16ab084d63ec9e3c6d71270d0cdd0d1675

Same with https://developer.github.com/v3/codes_of_conduct/#get-a-repositorys-code-of-conduct, it's the same route as https://developer.github.com/v3/repos/#get

**Comment by kytrinyx** [comment]
Oh! Looking at the codebase I have two different URLs that point to those two sections. I will sort this out with the docs team. Thanks!
