### ISSUE TITLE
URL Parameter Types -- `:number` and `:*_id`

### ISSUE THREAD

**Issue by kytrinyx** [octokit/routes#180]
I noticed that the URL parameters are all strings, even when they data they contain is an integer. Should we change the type definition of the `:number` and `:*_id` parameters to be `integer` rather than `string`?

**Comment by gr2m** [comment]
I think the `:number` parameters are all defined as integer already, I can’t recall a reason why the`*_id` parameters are string right now, I think we can change them to integer

**Comment by kytrinyx** [comment]
I found one that should not be an integer: `client_id`:

- https://github.com/octokit/routes/blob/master/routes/oauth-authorizations/get-or-create-an-authorization-for-a-specific-app-and-fingerprint.json
- https://github.com/octokit/routes/blob/master/routes/oauth-authorizations/get-or-create-an-authorization-for-a-specific-app.json

**Comment by gr2m** [comment]
shall we leave it as is then for now and but leave the issue open as a reminder?

**Comment by kytrinyx** [comment]
> shall we leave it as is then for now and but leave the issue open as a reminder?

Yes. I'm going to see if there's a fix we can make in the docs to avoid having URL parameters end in `_id` if they are strings.

If found one more. The `:user_id` in the SCIM API is an external guid, not an integer. https://developer.github.com/v3/scim/

**Comment by kytrinyx** [comment]
I'm asking the docs team if we can update `:user_id` to `:user_guid` for the SCIM API. For the OAuth API I'm afraid we're stuck with `:client_id` for the variable name, since in the OAuth domain, this is the correct term.

**Comment by gr2m** [comment]
> I'm asking the docs team if we can update :user_id to :user_guid for the SCIM API.

Great, thanks!

> For the OAuth API I'm afraid we're stuck with :client_id for the variable name, since in the OAuth domain, this is the correct term.

Easy enough to default to "integer" for `"_id"` properties and then add some exceptions with comments explaining why

**Comment by kytrinyx** [comment]
> Easy enough to default to "integer" for "_id" properties and then add some exceptions with comments explaining why

👍 That sounds perfectly reasonable!

**Comment by gr2m** [comment]
done via https://github.com/octokit/routes/pull/268
