### ISSUE TITLE
Publish as a Python package

### ISSUE THREAD

**Issue by andymckay** [octokit/routes#185]
Let's publish a Python version of this up to pypi. Most of the details are in #162, this is a seperate issue just to cover Python specifically.

**Comment by khornberg** [comment]
This would be nice. I use [Renovate](https://github.com/renovatebot/renovate) and it would keep [a python module](https://github.com/khornberg/octokit.py) update to date with the GitHub api.

**Comment by gr2m** [comment]
See my comment at https://github.com/octokit/routes/issues/162#issuecomment-438720166. Can we continue the discussion on #162?

**Comment by gr2m** [comment]
There is now https://github.com/khornberg/octokitpy-routes
