### ISSUE TITLE
Create a Pull Request from an existing Issue should have no head, base or maintainer_can_modify parameter

### ISSUE THREAD

**Issue by gr2m** [octokit/routes#200]
- endpoint scope: Pull Requests
- endpoint name: Create a Pull Request from an existing Issue
- route: `POST /repos/:owner/:repo/pulls`
- documentation URL: https://developer.github.com/v3/pulls/#alternative-input

### Current specification

https://github.com/octokit/routes/blob/d885a01bd0738f321742355e4bdc0d8a0d612240/routes/pulls/create-a-pull-request-from-an-existing-issue-by-passing-an-issue-number.json#L6-L49

### I expected

<details>
  <summary>Should have no <code>head</code>, <code>base</code> or <code> maintainer_can_modify</code> parameter</summary>

```json
{
  ...
  "params": [
    {
      "name": "owner",
      "type": "string",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
      "name": "repo",
      "type": "string",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
      "name": "issue",
      "type": "integer",
      "description": "The issue number in this repository to turn into a Pull Request.",
      "required": true,
      "location": "body"
    }
  ],
  ...
}
```
</details>

**Comment by kytrinyx** [comment]
As far as I can tell, `head` and `base` are required in both situations. `maintainer_can_modify` is accepted, but optional, if you pass `issue`.

**Comment by gr2m** [comment]
Thanks, all good then :)
