### ISSUE TITLE
Head sha parameter is not marked as required for Request Check Suites route

### ISSUE THREAD

**Issue by kytrinyx** [octokit/routes#231]
- endpoint scope: Checks
- endpoint name: Request check suites
- route: `/repos/:owner/:repo/check-suite-requests`
- documentation URL: https://developer.github.com/v3/checks/suites/#request-check-suites

### Current specification

https://github.com/octokit/routes/blob/7b1639f2ed0c28f8b0ea58d5dec2f11ab024266a/routes/checks/suites/request-check-suites.json#L21-L27

### I expected

The `required` property to be `true` on the `head_sha` parameter.

**Comment by gr2m** [comment]
The "Request Check Suites" route was replaced by "Rerequest check suite" https://developer.github.com/changes/2018-08-16-changes-to-the-checks-rest-api/
