### ISSUE TITLE
Broken default specification for docs

### ISSUE THREAD

**Issue by hiimbex** [octokit/routes#291]
https://octokit.github.io/rest.js/#api-Repos-createDeployment
octokit docs:

<img width="1271" alt="screen shot 2018-10-16 at 4 26 49 pm" src="https://user-images.githubusercontent.com/13410355/47045242-581a8a00-d160-11e8-8619-e8b947cf0a4d.png">

github docs:

<img width="668" alt="screen shot 2018-10-16 at 4 27 00 pm" src="https://user-images.githubusercontent.com/13410355/47045243-581a8a00-d160-11e8-9297-5d358a0ff87a.png">

Just guessing that the 'Default: `""`' is what's causing a parsing issue here.

**Comment by gr2m** [comment]
Wanna give it a try to fix it?

**Comment by hiimbex** [comment]
Sure!

It looks like it's being correctly generated by the routes into json:
https://github.com/octokit/routes/blob/751e746c987c14f881907d096f3cfd1008358a55/routes/repos/deployments/create-a-deployment-status.json#L60

So the issue could be in generating the docs for the website so maybe here:
https://github.com/octokit/rest.js/blob/f09b18629e9b084f4f13138b99a0f39138561ae9/scripts/generate-api-docs.js#L85-L88

Will try to make a fix!

**Comment by gr2m** [comment]
yeah looks like it’s the api docs generator script. Don’t worry too much about it, I hope we can replace these docs with something better soon :) Okay to close this issue as it’s not a problem with octokit/rest?

**Comment by hiimbex** [comment]
👍 yup! I kinda assuming it was a parsing issue, but yea, will not worry too much about it!
