### ISSUE TITLE
"List all topics for a repository" requires mercy preview

### ISSUE THREAD

**Issue by gr2m** [octokit/routes#356]
- endpoint scope: Repos
- endpoint name: List all topics for a repository
- route: `GET /repos/:owner/:repo/topics `
- documentation URL: https://developer.github.com/v3/repos/#list-all-topics-for-a-repository

The documentation does currently not state that the API cannot be used unless the mercy preview is requested via the accept header. We should implement a workaround until this will be corrected in the documentation

Reported at https://github.com/octokit/rest.js/pull/1230

### Current specification

https://github.com/octokit/routes/blob/f99a825f781bdc3d197d427ad25883801717d001/routes/api.github.com/repos/list-topics.json#L6-L12

### I expected

<details>
  <summary> mercy preview should be required: true</summary>

```json
{
  "name": "List all topics for a repository",
  "enabledForApps": true,
  "method": "GET",
  "path": "/repos/:owner/:repo/topics",
  "previews": [
    {
      "name": "mercy",
      "description": "**Note:** The `topics` property for repositories on GitHub is currently available for developers to preview. To view the `topics` property in calls that return repository results, you must provide a custom [media type](/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.mercy-preview+json\n\n```",
      "required": true
    }
  ],
  "params": [
    {
      "name": "owner",
      "type": "string",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
      "name": "repo",
      "type": "string",
      "required": true,
      "description": "",
      "location": "url"
    }
  ],
  "description": "",
  "responses": [
    {
      "headers": {
        "status": "200 OK",
        "content-type": "application/json; charset=utf-8"
      },
      "body": {
        "names": [
          "octocat",
          "atom",
          "electron",
          "API"
        ]
      }
    }
  ],
  "idName": "list-topics",
  "documentationUrl": "https://developer.github.com/v3/repos/#list-all-topics-for-a-repository"
}
```
</details>

**Comment by jenniferemshepherd** [comment]
This also applies to `replaceTopics` : https://github.com/octokit/routes/blob/f99a825f781bdc3d197d427ad25883801717d001/routes/api.github.com/repos/replace-topics.json#L6-L12

**Comment by taktran** [comment]
@gr2m can't the documentation just be fixed to allow `"required": true`?

**Comment by gr2m** [comment]
@taktran yes this needs to be fixed in the documentation itself at https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository

> Note: The `topics` property for repositories on GitHub is currently available for developers to preview. To view the `topics` property in calls that return repository results, you must provide a custom [media type](https://developer.github.com/v3/media) in the `Accept` header:
> 
> ```
> application/vnd.github.mercy-preview+json
> ```

This statement is incorrect, as the preview header is always required, not only to view the `topics` property like in other API endpoints.

@jenniferemshepherd could you write support@github.com to bring it to their attention? You can reference this issue, and please keep us posted 🙏 I can do it myself next week, I’m mostly offline unitl Monday

**Comment by jenniferemshepherd** [comment]
Hi @gr2m and @taktran, I have emailed Github and will let you know when I hear back. Thanks!

**Comment by jenniferemshepherd** [comment]
`Thanks for reporting this, Jennifer -- I've opened an internal issue so that the documentation team can consider making updates. I can't promise an ETA, but we'll followup as soon as there's any news.

The GitHub Support team will be participating in training sessions from July 6 through July 14. We will still be responding to tickets during this time, but you may experience a slight delay.`

**Comment by gr2m** [comment]
As this was still not addressed by the docs team and with [GitHub Universe](https://githubuniverse.com/) coming up and the team being surely busy with others things, I suggest we workaround this in octokit/routes for the time being.

I would add the workaround here:
https://github.com/octokit/routes/blob/master/lib/endpoint/overrides/workarounds.js

Help wanted :)

**Comment by copperwall** [comment]
I'm up to give this a shot.
