### ISSUE TITLE
OpenAPI: add GHE support

### ISSUE THREAD

**Issue by d11n** [octokit/routes#448]
@d11n I’ll look into the linting errors that are currently manually fixed in acc9d29. If you like, you can look into generating the OpenAPI spec for the GHE versions?

Feel free to clean up the code along the way :)

_Originally posted by @gr2m in https://github.com/octokit/routes/pull/168#issuecomment-506443139_

**Comment by gr2m** [comment]
FYI I cleaned up the linting errors. Will you try to implement the GHE routes?

**Comment by d11n** [comment]
yeah working on that now...hope to push up something tomorrow

**Comment by d11n** [comment]
resolved by #449
