### ISSUE TITLE
Change the payload action: started to action: starred for WatchEvent

### ISSUE THREAD

**Issue by starkblaze01** [octokit/routes#517]
- endpoint scope: Users
- endpoint name: Get the events performed by the user
- route: GET /users/:username/events
- documentation URL: https://developer.github.com/v3/activity/events/types/#watchevent

### Current specification

https://developer.github.com/v3/activity/events/types/#webhook-payload-example-43

### I expected the payload action to be ``starred`` instead of ``started``.

JSON:-
{
 "action": "starred",
...
}

**Comment by starkblaze01** [comment]
Hi, @gr2m the payload I am getting has action: started for WatchEvent, but shouldn't it be conventionally ``starred`` because right now WatchEvent occurs when a user stars a repository.
Thank You.

**Comment by gr2m** [comment]
I think it's a legacy thing. GitHub cannot just go an change the action name because it would break the existing integrations. I don't think there is anything we can do here

**Comment by starkblaze01** [comment]
Okay, thanks!
Closing this issue.
