### ISSUE TITLE
parameter type "array" should be "string[]" or "number[]"

### ISSUE THREAD

**Issue by gr2m** [octokit/routes#66]
- [ ] example for "numbers[]": https://github.com/octokit/routes/blob/fe0a25467e167c54628c2072884911a50c93269a/routes/orgs/members/create-organization-invitation.json#L37-L42
- [ ] example for "numbers[]": https://github.com/octokit/routes/blob/fe0a25467e167c54628c2072884911a50c93269a/routes/oauth-authorizations/create-a-new-authorization.json#L7-L12
- [x] Couldn’t find examples for "objects[]"

Has failing test at #77

**Comment by aryannarora** [comment]
PR opened #107 :)

**Comment by gr2m** [comment]
resolved in https://github.com/octokit/routes/pull/107
